### ISSUE TITLE
'MFKYC' is unavailable: cannot find Swift declaration for this class - Swift 4.2

### ISSUE THREAD

**Issue by AlexisLeon** [MatiFace/mati-global-id-sdk#1]
Is this SDK ready for production?

Installed with cocoapods: OK
Bitcode set to "No": OK
```swift
import MatiGlobalIDSDK

// then inside application didFinishLaunchingWithOptions:
MFKYC.register(clientId: "TOKEN HERE: YES")

// inside VC:
MFKYC.instance.delegate = self
```
Xcode Error: `'MFKYC' is unavailable: cannot find Swift declaration for this class`

**Comment by hovmush** [comment]
Please try to build your project on a real device, not on a simulator.

**Comment by AlexisLeon** [comment]
Now this: ```Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2.1 compiler```
Any plans to support Swift 4.2.x?

**Comment by AlexisLeon** [comment]
Thanks, Swift 4.2.x now supported in [0.0.7](https://github.com/MatiFace/mati-global-id-sdk/releases/tag/0.0.7)
