### ISSUE TITLE
Xcode 11.5: Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.2.4 compiler

### ISSUE THREAD

**Issue by dariovasconcelos** [MatiFace/mati-global-id-sdk#7]
Importing 'Mati-Global-ID-SDK' results in an error: Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.2.4 compiler.

The error is here: Mati-Global-ID-SDK/MatiGlobalIDSDK.framework/Modules/MatiGlobalIDSDK.swiftmodule/x86_64.swiftmodule

Apparently you need to rebuild it with a special flag so it can be rebuilt in future versions: 

> The provider of this library should rebuild it with BUILD_LIBRARY_FOR_DISTRIBUTION = YES; (available in Xcode 11.3 in Build Settings -> Build Options). 
https://stackoverflow.com/a/59406745/140441

Thanks!

**Comment by aposnovmati** [comment]
What version do you use? 
We long time ago use this flag, possibly with the beginning. Is it still a problem?
Could you check swift version in Pod settings?
